services:
  cliponomicon:
    build:
      context: .
      args:
        # Portainer tomará el valor de su pestaña "ENV" y se lo pasará al Dockerfile
        - VITE_API_URL=${API_URL}
    container_name: cliponomicon
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${API_URL}
    restart: unless-stopped