services:
  cliponomicon:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${API_URL}
    container_name: cliponomicon
    ports:
      - "${APP_PORT}:80"
    restart: unless-stopped
    networks:
      proxy_network:
        aliases:
          - ${PROXY_NETWORK_ALIAS}

    env_file:
      - path: stack.env
        required: false
      - path: .env
        required: false

networks:
  proxy_network:
    external: true
    name: ${PROXY_NETWORK_NAME}
