services:
  api-puente:
    build: .
    container_name: api-puente
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
