name: Deploy Luigi Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify webhook
        run: |
          curl -k -X POST "${{ secrets.COOLIFY }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"